# Generated by Django 5.0.4 on 2024-05-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='banner',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
